# Generated by Django 6.0.4 on 2026-04-20 07:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='joindate',
            field=models.DateField(default=datetime.datetime(2026, 4, 20, 9, 57, 13, 699713)),
        ),
    ]
