# Generated by Django 6.0.4 on 2026-04-21 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appy', '0004_user_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='image',
        ),
    ]
